/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'product_id' : bigint,
  'size' : Size,
  'quantity' : bigint,
}
export interface CatalogProduct {
  'id' : bigint,
  'imageUrls' : Array<string>,
  'name' : string,
  'color' : string,
  'description' : string,
  'availableSizes' : Array<Size>,
  'category' : string,
  'price' : bigint,
}
export interface Order {
  'status' : OrderStatus,
  'createdAt' : Time,
  'user_id' : Principal,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
  'totalPrice' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export type Size = { 'l' : null } |
  { 'm' : null } |
  { 's' : null } |
  { 'xl' : null } |
  { 'xs' : null } |
  { 'xxl' : null } |
  { 'xxxl' : null } |
  { 'unsized' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[Array<CartItem>, string], bigint>,
  'createCatalogProduct' : ActorMethod<
    [string, string, bigint, string, Array<string>, Array<Size>, string],
    bigint
  >,
  'fetchCatalogProduct' : ActorMethod<[bigint], CatalogProduct>,
  'fetchCatalogProductsByCategory' : ActorMethod<
    [string],
    Array<CatalogProduct>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTopCatalogProducts' : ActorMethod<[bigint], Array<CatalogProduct>>,
  'getTrendingCatalogProducts' : ActorMethod<[bigint], Array<CatalogProduct>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];