/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Size = IDL.Variant({
  'l' : IDL.Null,
  'm' : IDL.Null,
  's' : IDL.Null,
  'xl' : IDL.Null,
  'xs' : IDL.Null,
  'xxl' : IDL.Null,
  'xxxl' : IDL.Null,
  'unsized' : IDL.Null,
});
export const CartItem = IDL.Record({
  'product_id' : IDL.Nat,
  'size' : Size,
  'quantity' : IDL.Nat,
});
export const CatalogProduct = IDL.Record({
  'id' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
  'availableSizes' : IDL.Vec(Size),
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'status' : OrderStatus,
  'createdAt' : Time,
  'user_id' : IDL.Principal,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([IDL.Vec(CartItem), IDL.Text], [IDL.Nat], []),
  'createCatalogProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(Size),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'fetchCatalogProduct' : IDL.Func([IDL.Nat], [CatalogProduct], ['query']),
  'fetchCatalogProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CatalogProduct)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTopCatalogProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CatalogProduct)],
      ['query'],
    ),
  'getTrendingCatalogProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CatalogProduct)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Size = IDL.Variant({
    'l' : IDL.Null,
    'm' : IDL.Null,
    's' : IDL.Null,
    'xl' : IDL.Null,
    'xs' : IDL.Null,
    'xxl' : IDL.Null,
    'xxxl' : IDL.Null,
    'unsized' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'product_id' : IDL.Nat,
    'size' : Size,
    'quantity' : IDL.Nat,
  });
  const CatalogProduct = IDL.Record({
    'id' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
    'availableSizes' : IDL.Vec(Size),
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'status' : OrderStatus,
    'createdAt' : Time,
    'user_id' : IDL.Principal,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([IDL.Vec(CartItem), IDL.Text], [IDL.Nat], []),
    'createCatalogProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(Size),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'fetchCatalogProduct' : IDL.Func([IDL.Nat], [CatalogProduct], ['query']),
    'fetchCatalogProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CatalogProduct)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTopCatalogProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CatalogProduct)],
        ['query'],
      ),
    'getTrendingCatalogProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CatalogProduct)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };