/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface CartItem {
    product_id: bigint;
    size: Size;
    quantity: bigint;
}
export interface CatalogProduct {
    id: bigint;
    imageUrls: Array<string>;
    name: string;
    color: string;
    description: string;
    availableSizes: Array<Size>;
    category: string;
    price: bigint;
}
export interface Order {
    status: OrderStatus;
    createdAt: Time;
    user_id: Principal;
    shippingAddress: string;
    items: Array<CartItem>;
    totalPrice: bigint;
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered"
}
export enum Size {
    l = "l",
    m = "m",
    s = "s",
    xl = "xl",
    xs = "xs",
    xxl = "xxl",
    xxxl = "xxxl",
    unsized = "unsized"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkout(cart: Array<CartItem>, shippingAddress: string): Promise<bigint>;
    createCatalogProduct(name: string, description: string, price: bigint, category: string, imageUrls: Array<string>, availableSizes: Array<Size>, color: string): Promise<bigint>;
    fetchCatalogProduct(id: bigint): Promise<CatalogProduct>;
    fetchCatalogProductsByCategory(category: string): Promise<Array<CatalogProduct>>;
    getCallerUserRole(): Promise<UserRole>;
    getTopCatalogProducts(limit: bigint): Promise<Array<CatalogProduct>>;
    getTrendingCatalogProducts(limit: bigint): Promise<Array<CatalogProduct>>;
    getUserOrders(): Promise<Array<Order>>;
    isCallerAdmin(): Promise<boolean>;
}
import type { CartItem as _CartItem, CatalogProduct as _CatalogProduct, Order as _Order, OrderStatus as _OrderStatus, Size as _Size, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkout(arg0: Array<CartItem>, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createCatalogProduct(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>, arg5: Array<Size>, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCatalogProduct(arg0, arg1, arg2, arg3, arg4, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCatalogProduct(arg0, arg1, arg2, arg3, arg4, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async fetchCatalogProduct(arg0: bigint): Promise<CatalogProduct> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCatalogProduct(arg0);
                return from_candid_CatalogProduct_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCatalogProduct(arg0);
            return from_candid_CatalogProduct_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchCatalogProductsByCategory(arg0: string): Promise<Array<CatalogProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCatalogProductsByCategory(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCatalogProductsByCategory(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopCatalogProducts(arg0: bigint): Promise<Array<CatalogProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopCatalogProducts(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopCatalogProducts(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingCatalogProducts(arg0: bigint): Promise<Array<CatalogProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingCatalogProducts(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingCatalogProducts(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
}
function from_candid_CartItem_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CatalogProduct_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CatalogProduct): CatalogProduct {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Size_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Size): Size {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    imageUrls: Array<string>;
    name: string;
    color: string;
    description: string;
    availableSizes: Array<_Size>;
    category: string;
    price: bigint;
}): {
    id: bigint;
    imageUrls: Array<string>;
    name: string;
    color: string;
    description: string;
    availableSizes: Array<Size>;
    category: string;
    price: bigint;
} {
    return {
        id: value.id,
        imageUrls: value.imageUrls,
        name: value.name,
        color: value.color,
        description: value.description,
        availableSizes: from_candid_vec_n11(_uploadFile, _downloadFile, value.availableSizes),
        category: value.category,
        price: value.price
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    createdAt: _Time;
    user_id: Principal;
    shippingAddress: string;
    items: Array<_CartItem>;
    totalPrice: bigint;
}): {
    status: OrderStatus;
    createdAt: Time;
    user_id: Principal;
    shippingAddress: string;
    items: Array<CartItem>;
    totalPrice: bigint;
} {
    return {
        status: from_candid_OrderStatus_n20(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        user_id: value.user_id,
        shippingAddress: value.shippingAddress,
        items: from_candid_vec_n22(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    product_id: bigint;
    size: _Size;
    quantity: bigint;
}): {
    product_id: bigint;
    size: Size;
    quantity: bigint;
} {
    return {
        product_id: value.product_id,
        size: from_candid_Size_n12(_uploadFile, _downloadFile, value.size),
        quantity: value.quantity
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    l: null;
} | {
    m: null;
} | {
    s: null;
} | {
    xl: null;
} | {
    xs: null;
} | {
    xxl: null;
} | {
    xxxl: null;
} | {
    unsized: null;
}): Size {
    return "l" in value ? Size.l : "m" in value ? Size.m : "s" in value ? Size.s : "xl" in value ? Size.xl : "xs" in value ? Size.xs : "xxl" in value ? Size.xxl : "xxxl" in value ? Size.xxxl : "unsized" in value ? Size.unsized : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Size>): Array<Size> {
    return value.map((x)=>from_candid_Size_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CatalogProduct>): Array<CatalogProduct> {
    return value.map((x)=>from_candid_CatalogProduct_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n23(_uploadFile, _downloadFile, x));
}
function to_candid_CartItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Size_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): _Size {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    product_id: bigint;
    size: Size;
    quantity: bigint;
}): {
    product_id: bigint;
    size: _Size;
    quantity: bigint;
} {
    return {
        product_id: value.product_id,
        size: to_candid_Size_n6(_uploadFile, _downloadFile, value.size),
        quantity: value.quantity
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): {
    l: null;
} | {
    m: null;
} | {
    s: null;
} | {
    xl: null;
} | {
    xs: null;
} | {
    xxl: null;
} | {
    xxxl: null;
} | {
    unsized: null;
} {
    return value == Size.l ? {
        l: null
    } : value == Size.m ? {
        m: null
    } : value == Size.s ? {
        s: null
    } : value == Size.xl ? {
        xl: null
    } : value == Size.xs ? {
        xs: null
    } : value == Size.xxl ? {
        xxl: null
    } : value == Size.xxxl ? {
        xxxl: null
    } : value == Size.unsized ? {
        unsized: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Size>): Array<_Size> {
    return value.map((x)=>to_candid_Size_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
